package wsl2

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// jsonMarshalIndent is the indirection point for json.MarshalIndent so the
// "marshal failure" branch in savePortMappings is reachable from tests.
// marshalling map[string]int never fails in practice — this exists purely
// for coverage.
var jsonMarshalIndent = json.MarshalIndent

// wslConfigTemplate is the body written to <installDir>/.wslconfig when no
// global %USERPROFILE%\.wslconfig already exists. WSL2 only honours the
// global file, so this per-distro copy is informational — a hint for
// users who want to copy it into place themselves.
//
// The format is INI-ish (key=value under bracket sections); WSL parses
// memory as <N>GB / <N>MB and processors as a bare integer.
const wslConfigTemplate = `# Generated by Bolted (distro).
#
# WSL2 only reads %%USERPROFILE%%\.wslconfig at the global scope. This file
# is written under the Bolted install dir as a reference: copy it to
# %%USERPROFILE%%\.wslconfig (or merge its values) to apply the resources
# requested by ` + "`" + `bolt init` + "`" + `.
#
# See https://learn.microsoft.com/en-us/windows/wsl/wsl-config

[wsl2]
memory=%dMB
processors=%d
`

// renderWSLConfig produces the body of a .wslconfig file for the given
// spec. The disk size is intentionally not emitted — WSL2 ignores it
// (per-distro VHD growth is automatic up to a Windows-build-dependent
// cap).
func renderWSLConfig(memoryMB, cpus int) string {
	return fmt.Sprintf(wslConfigTemplate, memoryMB, cpus)
}

// writeWSLConfigHint writes the rendered .wslconfig under installDir and
// returns the path it wrote. If a global %USERPROFILE%\.wslconfig already
// exists, the function returns a non-empty warning string explaining
// what was (and was not) applied. The caller is responsible for logging
// the warning at whatever level it sees fit.
//
// The function never overwrites the user's global .wslconfig — that
// would be hostile. It only writes under installDir.
func writeWSLConfigHint(installDir string, memoryMB, cpus int, globalConfigExists bool) (path string, warning string, err error) {
	if err := os.MkdirAll(installDir, 0o755); err != nil {
		return "", "", fmt.Errorf("create install dir: %w", err)
	}
	path = filepath.Join(installDir, ".wslconfig")
	body := renderWSLConfig(memoryMB, cpus)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", "", fmt.Errorf("write %s: %w", path, err)
	}
	if globalConfigExists {
		warning = fmt.Sprintf(
			"a global .wslconfig already exists at %%USERPROFILE%%\\.wslconfig; the Bolted copy was written to %s but not applied. Merge values manually if you want Bolted's resource sizing.",
			path,
		)
	}
	return path, warning, nil
}

// portMappings is the on-disk representation of forwarded ports. Stored
// as JSON under <installDir>/ports.json. The map key is the host port; the
// value is the guest (in-distro) port.
type portMappings struct {
	// Mappings is host port -> guest port. JSON keys must be strings.
	Mappings map[string]int `json:"mappings"`
}

// portsFile is the on-disk location of the persisted forwards, relative
// to a Backend's installDir.
const portsFile = "ports.json"

// loadPortMappings reads the persisted mappings from installDir. A
// missing file is treated as an empty map (not an error) so first-run
// callers don't have to special-case it.
func loadPortMappings(installDir string) (portMappings, error) {
	path := filepath.Join(installDir, portsFile)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return portMappings{Mappings: map[string]int{}}, nil
		}
		return portMappings{}, fmt.Errorf("read %s: %w", path, err)
	}
	var m portMappings
	if err := json.Unmarshal(data, &m); err != nil {
		return portMappings{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if m.Mappings == nil {
		m.Mappings = map[string]int{}
	}
	return m, nil
}

// savePortMappings writes m to <installDir>/ports.json. The directory is
// created if missing.
func savePortMappings(installDir string, m portMappings) error {
	if err := os.MkdirAll(installDir, 0o755); err != nil {
		return fmt.Errorf("create install dir: %w", err)
	}
	if m.Mappings == nil {
		m.Mappings = map[string]int{}
	}
	// Marshal with sorted keys for stable on-disk output (helps diff
	// reviews and avoids spurious changes in test fixtures).
	keys := make([]string, 0, len(m.Mappings))
	for k := range m.Mappings {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	ordered := struct {
		Mappings map[string]int `json:"mappings"`
	}{Mappings: make(map[string]int, len(keys))}
	for _, k := range keys {
		ordered.Mappings[k] = m.Mappings[k]
	}
	data, err := jsonMarshalIndent(ordered, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal port mappings: %w", err)
	}
	path := filepath.Join(installDir, portsFile)
	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// formatEnv joins KEY=VALUE pairs into a single string suitable for
// prepending to a `sh -c` payload. Each value is shell-quoted so spaces
// and quotes inside the value do not break the resulting command line.
// The output ends with a trailing space when env is non-empty so the
// caller can concatenate the command verbatim.
func formatEnv(env []string) string {
	if len(env) == 0 {
		return ""
	}
	parts := make([]string, 0, len(env))
	for _, e := range env {
		eq := strings.IndexByte(e, '=')
		if eq <= 0 {
			// Skip malformed entries (no '=' or empty key) — matches
			// os/exec.Cmd.Env behaviour of ignoring them silently.
			continue
		}
		key := e[:eq]
		val := e[eq+1:]
		parts = append(parts, fmt.Sprintf("%s=%s", key, shellQuote(val)))
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " ") + " "
}

// shellQuote wraps s in single quotes and escapes any embedded single
// quotes so the result is safe to pass to `sh -c`. It is intentionally
// minimal — POSIX single-quoting is enough for our needs and avoids the
// edge cases of double-quote expansion.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	// Escape ' as '\'' inside the surrounding ' … '.
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
